num = input('Informe um número de 4 digitos: ').strip()
print('Analisando o número {}'.format(num))
print('Unidade: ',num[3])
print('Dezena: ',num[2])
print('Centena: ',num[1])
print('Milhar: ',num[0])
